---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-chart
  labels:
    app.kubernetes.io/name: nginx-chart
    helm.sh/chart: {{include "nginx-chart.chart" .}}
    app.kubernetes.io/instance: nginx-chart
    app.kubernetes.io/managed-by: {{.Release.Service}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-chart
      app.kubernetes.io/instance: nginx-chart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-chart
        app.kubernetes.io/instance: nginx-chart
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      containers:
        - name: nginx-chart
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: efs-logs
              mountPath: /var/log/nginx
              # Mount EFS here for logs
      volumes:
        - name: efs-logs
          persistentVolumeClaim:
            claimName: efs-pvc-nginx
