---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-nginx
spec:
  capacity:
    storage: 1Gi
    # This is required but ignored by EFS
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
    # EFS supports multiple writers
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  # Must match the StorageClass for your EFS CSI Driver
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{.Values.efs.fileSystemId}}
    # EFS File System ID from values.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-nginx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
      # This request is needed; EFS will automatically scale
  storageClassName: efs-sc
