---
apiVersion: v1
kind: Service
metadata:
  name: nginx-chart
  labels:
    app.kubernetes.io/name: nginx-chart
    app.kubernetes.io/instance: nginx-chart
spec:
  selector:
    app.kubernetes.io/name: nginx-chart
    app.kubernetes.io/instance: nginx-chart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
