---
apiVersion: v1
kind: Service
metadata:
  name: frontend-chart
  labels:
    app.kubernetes.io/name: frontend-chart
    app.kubernetes.io/instance: frontend-chart
spec:
  selector:
    app.kubernetes.io/name: frontend-chart
    app.kubernetes.io/instance: frontend-chart
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
