---
apiVersion: v1
kind: Service
metadata:
  name: javascript-chart
  labels:
    app.kubernetes.io/name: javascript-chart
    app.kubernetes.io/instance: javascript-chart
spec:
  selector:
    app.kubernetes.io/name: javascript-chart
    app.kubernetes.io/instance: javascript-chart
  ports:
    - protocol: {{.Values.ports.protocol}}
      port: {{.Values.ports.port}}
      targetPort: {{.Values.ports.targetPort}}
  type: {{.Values.service.type}}
