---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: laravel-api-sa
  namespace: {{.Release.Namespace}}
  # Use the namespace from Helm release
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::772728963654:role/api-token-access
